
# THIS CODE WAS AUTO GENERATED BY 'parameterize_inst.v.mako'

module example (
  input clk
  input rst
  
  input i_ex
  output o_ex
 )
 
//------------------------
// Instance 0
// Input-Output declarations
reg  [31:0] EXAMPLE_0; 

...
//------------------------
// Instance 1
// Input-Output declarations
reg  [31:0] EXAMPLE_1; 

...
//------------------------
// Instance 2
// Input-Output declarations
reg  [31:0] EXAMPLE_2; 

...
//------------------------
// Instance 3
// Input-Output declarations
reg  [31:0] EXAMPLE_3; 

...
//------------------------
// Instance 4
// Input-Output declarations
reg  [31:0] EXAMPLE_4; 

...
//------------------------
// Instance 5
// Input-Output declarations
reg  [31:0] EXAMPLE_5; 

...
//------------------------
// Instance 6
// Input-Output declarations
reg  [31:0] EXAMPLE_6; 

...
