<%!
import math
from collections import deque
def log2(x): return int(math.ceil(math.log(x, 2)))
%>
# THIS CODE WAS AUTO GENERATED BY 'parameterize_inst.v.mako'

module example (
  input clk
  input rst
  
  input i_ex
  output o_ex
 )
 
% for i in range (n):
//------------------------
// Instance ${i}
// Input-Output declarations
reg  [31:0] EXAMPLE_${i}; 

...
% endfor